### ISSUE TITLE
Problem overriding libexecdir

### ISSUE THREAD

**Issue by jbicha** [ebassi/graphene#100]
For Debian, we want the installed tests to end up in `/usr/lib/installed-tests/graphene-1.0/`
So I used the meson flag `-Dlibexecdir=/usr/lib` but the tests were still installed to `/usr/libexec/`

**Comment by TingPing** [comment]
Note when invoking `meson` it is `--libexecdir` not `-Dlibexecdir`

**Comment by jbicha** [comment]
Thanks. That fixed my issue.

**Comment by TingPing** [comment]
For future reference there is mesonbuild/meson#969 over this ambiguity.
