### ISSUE TITLE
Build error on Ubuntu

### ISSUE THREAD

**Issue by tamimcse** [ebassi/graphene#103]
Hi

I'm getting the following compile error on Ubuntu 16.04

Checking for function "aligned_alloc": NO
Checking for function "memalign": NO
Checking for function "posix_memalign": YES
Checking for function "sincosf": YES
Library m found: YES
Dependency threads found: YES
Found pkg-config: /usr/bin/pkg-config (0.29.1)
Native dependency gobject-2.0 found: YES 2.48.2
Program g-ir-scanner found: NO
Checking if "SSE intrinsics" compiles: YES
Checking if "GCC vector intrinsics" compiles: YES
Checking if "ARM NEON intrinsics" compiles: NO
Configuring config.h using configuration
Configuring graphene-config.h using configuration
Configuring graphene-version.h using configuration

Meson encountered an error in file src/meson.build, line 108, column 0:
Tried to form an absolute path to a source dir. You should not do that but use
relative paths instead.

Could you please advise me what is wrong here? Is there a way to install Graphene
 from package manager? I see https://launchpad.net/ubuntu/zesty/+source/graphene, but I'm not sure how to get PPA URL from here. 

Thanks!

**Comment by TingPing** [comment]
Should be fixed by https://github.com/ebassi/graphene/commit/a0f8893e82f5d9ea5555b35ae35243cf80126b2a

**Comment by ebassi** [comment]
@tamimcse You didn't add all the necessary information:

 - which version of Graphene is this?
 - which version of Meson is this?

There isn't anything related to paths in `src/meson.build` at line 108 in either the master nor the graphene-1-6 branches.

**Comment by tamimcse** [comment]
Graphene 1.4.1
Meson 0.39.1.

**Comment by ebassi** [comment]
Graphene 1.4.1 is not master: it's two releases ago. The current stable version of Graphene is 1.6.0, and it still builds by default with autotools.

Only the master branch (1.7.1) requires Meson.

In any case, I can see the issue, and it'll be fixed momentarily.
