### ISSUE TITLE
Multiple places for option handling in configure

### ISSUE THREAD

**Issue by inigomartinez** [ebassi/graphene#104]
### Experienced behavior

If any option is added to meson, there are multiple places in the configure scripts to be modified to add proper support..

### Expected behavior

Easier way to add an option to meson by adding only the option name and its default value.

### Steps to reproduce

Add a new option to mesa.

**Comment by ebassi** [comment]
I'm sorry, but I don't understand this issue.

What is it that you're trying to achieve?

**Comment by inigomartinez** [comment]
Oh, I was opening the pull request by following the "Contributing" notes. This patch tries to simplify the configure script.

**Comment by ebassi** [comment]
We dropped the Autotools build, and we don't use a build-api wrapper any more.
