### ISSUE TITLE
Allocation problems in Python

### ISSUE THREAD

**Issue by lubosz** [ebassi/graphene#11]
What are graphene's plans for gobject introspection? Will it be still supported, despite the "de-glib-ify" branch?

I would like to use graphene in Pitivi for OpenGL, as I suppose many other Python users would find very useful.

These issues need likely to be reported to gobject-introspection or python-gobject, I will collect them here to have an overview though.

Examples
---------------------

### Segmentation fault on print_()

This snipped crashes on the last print statement.

```python
#!/usr/bin/env python3

from gi.repository import Graphene

mat = Graphene.Matrix()
mat.alloc()
mat.print_()
mat.init_identity()
mat.print_()
```
Backtrace

    #0  0x00007ffff5cb8890 in g_slist_length () at /usr/lib/libglib-2.0.so.0
    #1  0x00007ffff6657721 in  () at /usr/lib/python3.4/site-packages/gi/_gi.cpython-34m.so
    #2  0x00007ffff664d49e in  () at /usr/lib/python3.4/site-packages/gi/_gi.cpython-34m.so
    #3  0x00007ffff79a8e68 in PyObject_Call (func=func@entry=0x7ffff4722810, arg=arg@entry=0x7ffff7fba048, kw=kw@entry=0x0) at Objects/abstract.c:2067
    #4  0x00007ffff7a58e49 in PyEval_EvalFrameEx (nk=<optimized out>, na=0, pp_stack=0x7fffffffe070, func=<optimized out>) at Python/ceval.c:4456
    #5  0x00007ffff7a58e49 in PyEval_EvalFrameEx (oparg=<optimized out>, pp_stack=0x7fffffffe070)
        at Python/ceval.c:4254
    #6  0x00007ffff7a58e49 in PyEval_EvalFrameEx (f=0x7ffff6c13438, throwflag=<optimized out>)
        at Python/ceval.c:2829
    #7  0x00007ffff7a5f289 in PyEval_EvalCodeEx (_co=0x3f800000, 
        _co@entry=0x7ffff6bd5390, globals=0x0, locals=0x7ffff6c135b0, args=0x0, argcount=argcount@entry=0, kws=kws@entry=0x0, kwcount=0, defs=0x0, defcount=0, kwdefs=0x0, closure=0x0) at Python/ceval.c:3578
    #8  0x00007ffff7a5f32b in PyEval_EvalCode (co=co@entry=0x7ffff6bd5390, globals=globals@entry=0x7ffff6c11408, locals=locals@entry=0x7ffff6c11408) at Python/ceval.c:773
    #9  0x00007ffff7a7b4d4 in run_mod (mod=mod@entry=0x6f5c40, filename=filename@entry=0x7ffff6b111f0, globals=globals@entry=0x7ffff6c11408, locals=locals@entry=0x7ffff6c11408, flags=flags@entry=0x7fffffffe2f0, arena=arena@entry=0x6e0450) at Python/pythonrun.c:2180
    #10 0x00007ffff7a7d705 in PyRun_FileExFlags (fp=0x6e0210, filename_str=<optimized out>, start=<optimized out>, globals=0x7ffff6c11408, locals=0x7ffff6c11408, closeit=1, flags=0x7fffffffe2f0)
        at Python/pythonrun.c:2133
    #11 0x00007ffff7a7e6d3 in PyRun_SimpleFileExFlags (fp=0x3f800000, filename=0x7ffff6c08740 "./bug.py", closeit=1, flags=0x0) at Python/pythonrun.c:1606
    #12 0x00007ffff7a948bc in Py_Main (p_cf=<optimized out>, filename=<optimized out>, fp=<optimized out>)
        at Modules/main.c:319
    #13 0x00007ffff7a948bc in Py_Main (argc=-156168016, argv=0x7ffff6c08720) at Modules/main.c:751
    #14 0x0000000000400af6 in main ()

### Uninitialized Memory on init_identity()
   
Two values of the matrix are not initialized properly. This happens when the calls happen on the same object and not on the return value.
    
```python
#!/usr/bin/env python3

from gi.repository import Graphene

mat = Graphene.Matrix()
mat.alloc()
mat.init_identity()

# same result when initialized like this
# mat = Graphene.Matrix()
# Graphene.Matrix.init_identity(mat)

mat.print_()

foo = mat.to_float()

print(foo)
```
    
Output

    1.00000 0.00000 0.00000 0.00000
    0.00000 1.00000 0.00000 0.00000
    0.00000 0.00000 1.00000 0.00000
    0.00000 0.00000 0.00000 0.00000
    [1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.9769944729427674e-38, 0.0, 2.2420775429197073e-44, 0.0]

### Segfault on to_float()

Here we get correctly initialized values, because the operations are done on the return values, rather than in place. It segfaults when calling to_float() though. The print_() and get_value() functions work thought.

```python
#!/usr/bin/env python3

from gi.repository import Graphene

mat = Graphene.Matrix()
mat2 = mat.alloc()
mat3 = mat2.init_identity()

mat.print_()
print("#")
mat2.print_()
print("#")
mat3.print_()

foo = mat3.to_float()
```
Output

    0.00000 0.00000 0.00000 0.00000
    0.00000 0.00000 0.00000 0.00000
    0.00000 0.00000 0.00000 0.00000
    0.00000 0.00000 0.00000 0.00000
    #
    1.00000 0.00000 0.00000 0.00000
    0.00000 1.00000 0.00000 0.00000
    0.00000 0.00000 1.00000 0.00000
    0.00000 0.00000 0.00000 1.00000
    #
    1.00000 0.00000 0.00000 0.00000
    0.00000 1.00000 0.00000 0.00000
    0.00000 0.00000 1.00000 0.00000
    0.00000 0.00000 0.00000 1.00000
    Segmentation fault

Backtrace

    #0  0x00007ffff5cb7055 in g_slice_alloc () at /usr/lib/libglib-2.0.so.0
    #1  0x00007ffff5c6f825 in g_array_sized_new () at /usr/lib/libglib-2.0.so.0
    #2  0x00007ffff665b20a in  () at /usr/lib/python3.4/site-packages/gi/_gi.cpython-34m.so
    #3  0x00007ffff66580eb in  () at /usr/lib/python3.4/site-packages/gi/_gi.cpython-34m.so
    #4  0x00007ffff664d49e in  () at /usr/lib/python3.4/site-packages/gi/_gi.cpython-34m.so
    #5  0x00007ffff79a8e68 in PyObject_Call (func=func@entry=0x7ffff471e880, arg=arg@entry=0x7ffff7fba048, kw=kw@entry=0x0) at Objects/abstract.c:2067
    #6  0x00007ffff7a58e49 in PyEval_EvalFrameEx (nk=<optimized out>, na=0, pp_stack=0x7fffffffe070, func=<optimized out>) at Python/ceval.c:4456
    #7  0x00007ffff7a58e49 in PyEval_EvalFrameEx (oparg=<optimized out>, pp_stack=0x7fffffffe070) at Python/ceval.c:4254
    #8  0x00007ffff7a58e49 in PyEval_EvalFrameEx (f=0x7ffff6c13438, throwflag=<optimized out>) at Python/ceval.c:2829
    #9  0x00007ffff7a5f289 in PyEval_EvalCodeEx (_co=0x20, 
        _co@entry=0x7ffff6bd5390, globals=0x0, locals=0x7ffff6c135b0, args=0x0, argcount=argcount@entry=0, kws=kws@entry=0x0, kwcount=0, defs=0x0, defcount=0, kwdefs=0x0, closure=0x0) at Python/ceval.c:3578
    #10 0x00007ffff7a5f32b in PyEval_EvalCode (co=co@entry=0x7ffff6bd5390, globals=globals@entry=0x7ffff6c11408, locals=locals@entry=0x7ffff6c11408) at Python/ceval.c:773
    #11 0x00007ffff7a7b4d4 in run_mod (mod=mod@entry=0x6f6470, filename=filename@entry=0x7ffff6b111f0, globals=globals@entry=0x7ffff6c11408, locals=locals@entry=0x7ffff6c11408, flags=flags@entry=0x7fffffffe2f0, arena=arena@entry=0x677610) at Python/pythonrun.c:2180
    #12 0x00007ffff7a7d705 in PyRun_FileExFlags (fp=0x6773d0, filename_str=<optimized out>, start=<optimized out>, globals=0x7ffff6c11408, locals=0x7ffff6c11408, closeit=1, flags=0x7fffffffe2f0)
        at Python/pythonrun.c:2133
    #13 0x00007ffff7a7e6d3 in PyRun_SimpleFileExFlags (fp=0x20, filename=0x7ffff6c08740 "./bug.py", closeit=1, flags=0x7dd4c0) at Python/pythonrun.c:1606
    #14 0x00007ffff7a948bc in Py_Main (p_cf=<optimized out>, filename=<optimized out>, fp=<optimized out>) at Modules/main.c:319
    #15 0x00007ffff7a948bc in Py_Main (argc=-156168016, argv=0x7ffff6c08720) at Modules/main.c:751
    #16 0x0000000000400af6 in main ()

### JavaScript to_float()

In JavaScript the initialization seems to work correctly, but the runtime does not allow to call to_float at all.
```javascript
#!/usr/bin/env gjs
     
const Graphene = imports.gi.Graphene;

let mat = new Graphene.Matrix();
mat.alloc();
mat.init_identity();
mat.print();

let foo = mat.to_float();
```

Output

    1.00000 0.00000 0.00000 0.00000
    0.00000 1.00000 0.00000 0.00000
    0.00000 0.00000 1.00000 0.00000
    0.00000 0.00000 0.00000 1.00000

    (gjs:3095): Gjs-WARNING **: JS ERROR: Error: Unsupported type array for (out caller-allocates)
    @./bug.js:11

    JS_EvaluateScript() failed

**Comment by ebassi** [comment]
I can definitely use Graphene from Python, and I wrote an initial note on the wiki about constructors: https://github.com/ebassi/graphene/wiki/Using-Graphene-from-Python

I consider this issue closed.
