### ISSUE TITLE
GCC gnu89

### ISSUE THREAD

**Issue by dirkson** [ebassi/graphene#126]
Heyo!

Trying to build graphene using -std=gnu89 on GCC 8.2 results in errors that "__STDC_VERSION__" is not defined. Which makes sense, as __STDC_VERSION__ is not required to be defined in that version of C.

This may or may not be considered a problem, but I figured it was worth a note anyway.

It appears you check for this to determine C11 support. I'm curious what differences a graphene build has for C11 - Is that documented anywhere?

Cheers!

**Comment by ebassi** [comment]
> Trying to build graphene using -std=gnu89

There's a reason why we use `c_std=c99` as a default option [in the Meson configuration](https://github.com/ebassi/graphene/blob/master/meson.build#L7). I don't plan on supporting C89 with or without GCC extensions, in 2018. Graphene itself exposes C99 constructs, like C99's `__STDC_VERSION__` pre-defined macro, `_Bool` type, and compound literals. We only have fallbacks in place for MSVC, but I routinely drop older versions of that compiler.

The C11 support is for the `_Generic` pragma, and it's only [used internally](https://github.com/ebassi/graphene/blob/master/src/graphene-private.h#L131-L148) to use the appropriate linear interpolation function depending on the input type, and avoid a cast or a type promotion.
