### ISSUE TITLE
Clang compatibility issue

### ISSUE THREAD

**Issue by dirkson** [ebassi/graphene#159]
### Experienced behavior

When being built as a standalone project using clang, somehow both -Wall and -Wunused fail to convert a clang warning into an error.

The warning in question is: ../src/graphene-matrix.c:1594:1: warning: unused function 'graphene_matrix_transpose_transform_vec4' [-Wunused-function]

This warning DOES occur when travisCI is run: https://travis-ci.org/ebassi/graphene/jobs/548740495

Also, that particular travisCI job says the clang version is both 3.8 and 5.0, which seems weird.

When graphene is instead built as a subproject using clang, this warning IS converted to an error, and as a result graphene cannot be used as a a subproject in another project.

I'm not at all sure this isn't a meson or clang issue, but your knowledge of meson build files is better than mine, so I figure opening an issue with you is a good next step.

### Expected behavior

The warning should always convert into an error, failing the travisCI build and forcing the removal of the warning through clever source code wizardry.

### Steps to reproduce

Your travisCI build is already reproducing this issue consistently.

### Operating system in use

Void linux for mine. Unsure what travis uses. Magic probably.

Cheers,
-Dirk

**Comment by ebassi** [comment]
Thanks for the detailed issue! Much appreciated.

> Also, that particular travisCI job says the clang version is both 3.8 and 5.0, which seems weird.

Clang 5.0 is the backported version shipped by the base Ubuntu CI runner; 3.8 is the version of Clang in the Docker image I use to run the job, and it's coming from Debian Stretch.
