### ISSUE TITLE
graphene-config.h localization

### ISSUE THREAD

**Issue by neurotok** [ebassi/graphene#172]
Is there any particular reason why libgraphene-1.0-dev on debian-ish distributions is throwing graphene-config.h into

/usr/lib/x86_64-linux-gnu/graphene-1.0/include/  ?

It is so painful to include it into any larger build system :( at the end i had to do

sudo cp /usr/lib/x86_64-linux-gnu/graphene-1.0/include/graphene-config.h /usr/include/graphene-1.0/

to move my project forward

**Comment by ebassi** [comment]
The `graphene-config.h` header is system dependent, which means it **cannot** go in the global include directory. The appropriate place for this kind of headers is a directory under `libdir`.

> It is so painful to include it into any larger build system :(

It's really not, if you are using `pkg-config --cflags graphene-1.0` to gather the compiler flags to be used when building code that depends on Graphene—which is how Graphene should be integrated in *any* build system.

Most definitely you should **never** move files installed by your distro around.

**Comment by Igittigitt24** [comment]
I had graphene-config.h stored under libdir, but the compiler (PellesC) ignored it totally, so I HAD TO copy it to the other .h-files!
Is that an error of PellesC only?

**Comment by ebassi** [comment]
You need to pass the right compiler flags to your C compiler, which is what pkg-config provides.
