### ISSUE TITLE
Missing graphene-gobject.h

### ISSUE THREAD

**Issue by gvanem** [ebassi/graphene#184]
I tried using the Artifacts of this repo to build the Gnome package [Gsk](https://gitlab.gnome.org/GNOME/gtk/-/tree/master/gsk).

But hit a problem with a  missing `graphene-gobject.h` included in [`gskrenderer.c`](https://gitlab.gnome.org/GNOME/gtk/-/blob/master/gsk/gskrenderer.c#L47)
Is this header not public or are we supposed to build Graphene ourself?

**Comment by ebassi** [comment]
I assume you're talking about building GTK from the current development branch on Windows.

The release artefacts linked from each Graphene release are:

 - `graphene-$version.tar.xz`: the dist tarball generated by `meson dist`, which contains only source files
 - `graphene-shared-x86.zip`: the binary build using MSVC on x86
 - `graphene-shared-x64.zip`: the binary build using MSVC on x86_64

The latter two only contain Graphene without any GObject extension or documentation.

If you want to build GTK on Windows with MSVC, I recommend reading [the GTK documentation](https://www.gtk.org/docs/installations/windows/), and use [gsvbuild](https://github.com/wingtk/gvsbuild).

**Comment by gvanem** [comment]
You assumed correctly, but I've tried gsvbuild and it fails miserably.

**Comment by ebassi** [comment]
>  I've tried gsvbuild and it fails miserably.

That's something you'll have to bring up to the gsvbuild developers, I'm afraid.
