### ISSUE TITLE
_isnanf on Windows instead of isnanf

### ISSUE THREAD

**Issue by vtorri** [ebassi/graphene#185]
in src/graphene-ray.c, isnanf does not exist on Windows, but _isnanf does  :
 
https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/isnan-isnan-isnanf?view=vs-2019

would it be possible do something like

```
#if defined _WIN32 && ! defined isnanf
# define isnanf(x) _isnanf(x)
#endif
```

at the top of graphene-ray.c for example ?

then maybe the check os isnanf in meson.buikd on Windows is useless

thank you

**Comment by vtorri** [comment]
also, one should define HAVE_ISNANF in it. So

```
#if defined _WIN32 && ! defined isnanf
# define isnanf(x) _isnanf(x)
# define HAVE_ISNANF
#endif
```

**Comment by ebassi** [comment]
Thanks for your patience.

Would you care to put together a merge request?
