### ISSUE TITLE
2d bounding boxes

### ISSUE THREAD

**Issue by matthiasclasen** [ebassi/graphene#204]
GTK uses graphene_rect_t for 2d bounding boxes in a number of places, but its representation as origin+size makes is somewhat unsuitable for that use. Issues:
- due to floating point rounding, a a rect around p1, p2 may not actually contain p2
- intersecting rects with empty interior (such as bounding boxes for axis-aligned line segments) returns FALSE

graphene_box_t seems to be made for bounding box uses, and uses a min-max representation internally, but it has that extra z. It would be nice to have a graphene_box2d_t

**Comment by matthiasclasen** [comment]
I have no deep thoughts on that. The main operations I foresee on a bounding box type are:
- containment/overlap checks (for points and rects)
- unions

**Comment by ebassi** [comment]
The PR in #259 contains an implementation of an AABB.
