### ISSUE TITLE
Link in sidebar should go to github.io not github.com

### ISSUE THREAD

**Issue by heyLu** [ebassi/graphene#228]
Hi, the link in the sidebar should go to https://ebassi.github.io/graphene/ instead of https://ebassi.github.com/graphene/.

![2021-04-26-wrong-link](https://user-images.githubusercontent.com/527119/116058985-adfd1080-a680-11eb-8277-5ad470c4463f.png)

Apologies for the superfluous ticket, I figured that was the quickest way to get in contact.

Have a nice day! :wave:

**Comment by ebassi** [comment]
Indeed! Thanks for reporting the issue.
