### ISSUE TITLE
cannot open source file "graphene-config.h" (dependency of "gtk/gtk.h") HELP!????

### ISSUE THREAD

**Issue by VeryChubbyCats** [ebassi/graphene#264]
I have tried everything to fix this.

Here is what I added to my path.

"${workspaceFolder}/**",
"/usr/include/linux",
"/usr/include/gtk-4.0",
"/usr/include/glib-2.0",
"/usr/lib64/glib-2.0/include",
"/usr/include/pango-1.0",
"/usr/include/harfbuzz"
"/usr/include/cairo",
"/usr/include/gdk-pixbuf-2.0",
"/usr/include/graphene-1.0"

This a problem with VS code's extension not the compiler. The compiler work's perfectly fine.

Programming lang" C
Attempting to use: Gtk 4 devel

Help?

**Comment by ebassi** [comment]
Sorry, but I don't use VSCode.

You should ask on a support forum for VS Code: Graphene provides a pkg-config file for finding all headers and setting all the compiler/linker flags; you should be able to use that file to set up the build environment.

I'll just say that the `graphene-config.h` header file is an architecture/platform-specific file, which means it's going to be located under `/usr/lib64/graphene-1.0/include`, assuming that graphene has been installed under `/usr` and that the library directory is `/usr/lib64`.
