### ISSUE TITLE
Are there any prebuilt binary packages?

### ISSUE THREAD

**Issue by axefrog** [ebassi/graphene#37]
I'm having a lot of trouble getting through a successful build (see my other issue). Are you aware of any prebuilt binary packages (i.e. libs+headers I can compile and link against) available anywhere for download? I'm developing on Windows but also wish to offer builds of my application for OSX and Linux. Support for ARM and others is not important to me at this stage.

**Comment by ebassi** [comment]
no, I don't have prebuilt binaries for Graphene. I can probably cross-compile for Windows on Linux, but right now I don't have spare cycles for it.

**Comment by axefrog** [comment]
No worries, thanks for replying. I went with GLM for now.
