### ISSUE TITLE
make check fails

### ISSUE THREAD

**Issue by tschoonj** [ebassi/graphene#41]
on Mac OS X Yosemite with graphene 1.2.4:

````
ERROR: quaternion - missing test plan
ERROR: quaternion - exited with status 134 (terminated by signal 6?)
````

**Comment by ebassi** [comment]
Can you try running the `quaternion` test by itself, and see why it's aborting?

**Comment by tschoonj** [comment]
I get the following output:

````
/quaternion/init: OK
/quaternion/operators/invert: OK
/quaternion/operators/dot: **
Graphene:ERROR:quaternion.c:33:quaternion_operators_dot: assertion failed (graphene_quaternion_dot (&q1, &q2) == -3.f): (-3.87258632e+25 == -3)
Abort trap: 6
````

**Comment by ebassi** [comment]
That's interesting. Which compiler did you use to build Graphene?

**Comment by tschoonj** [comment]
Clang



Op 14-aug.-2015 om 11:00 heeft Emmanuele Bassi <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


That's interesting. Which compiler did you use to build Graphene?

**Comment by ebassi** [comment]
I think commit 7b9381a I just pushed to master fixes the issue.

**Comment by tschoonj** [comment]
Yes it did!

Thanks
