### ISSUE TITLE
column major

### ISSUE THREAD

**Issue by teamblubee** [ebassi/graphene#45]
Hi

Is your matrix math column or row major ordering? I was wrangling with sony's vectormath library and while the math is good the api is really terrible [in my opinion]. You seem to have a reasonable api with neon and sse support. Do your matrices work with column major or row major?

Also do you provide a cmake build?

**Comment by ebassi** [comment]
From the [graphene_matrix_t API reference](http://ebassi.github.io/graphene/docs/graphene-Matrix.html#graphene-Matrix.description):

> The matrix is treated as row-major, i.e. it has four vectors (x, y, z, and w) representing rows, and elements of each vector are a column

But when converting from and to floating point C arrays the memory layout is compatible with column-major interpretations like GL or DirectX.

I don't use or know CMake, so I don't have a CMake build. I'm not formally against having a parallel CMake build, but I would not be able to maintain it myself, so I would not be able to fix it if/when it breaks.
