### ISSUE TITLE
GObject support: make the CamelCase types available in C

### ISSUE THREAD

**Issue by swilmet** [ebassi/graphene#46]
There is no typedefs in graphene-gobject.h, so the CamelCase types are not available in C, just for languages like Python, JS, etc. But when reading the documentation, I thought that the CamelCase types were also available in C.

I have a patch almost ready for this, the gtk-doc comments just need to be written and it should work fine.

When using only GLib-based libraries in an application, it's nice to have all types in CameCase, it makes the code consistent.

**Comment by ebassi** [comment]
I really dislike this. Cairo, which is pretty much the template for this kind of thing, does not expose a `typedef cairo_t CairoContext`.

The reason we need the camel case types is because of gobject-introspection; I don't want to deal with them at the C level.

**Comment by swilmet** [comment]
Ok, I'll improve the docs then, because it was not clear to me. Basically graphene-gobject.h should not be used in C.

**Comment by ebassi** [comment]
The only thing that `graphene-gobject.h` does is provide the GType for Graphene types in case they are used for properties and signal marshallers. It does not change the API, not it "fixes" it for GObject consumers. C developers are still expected to use the Graphene C API.
