### ISSUE TITLE
graphene_rect_union(): schema and implementation mismatch

### ISSUE THREAD

**Issue by swilmet** [ebassi/graphene#49]
I see that you've added schemas, that's nice.

But for graphene_rect_union(), the implementation doesn't do what the schema shows:

```
res->origin.x = MIN (ra.origin.x, rb.origin.x);
res->origin.y = MIN (ra.origin.y, rb.origin.y);

res->size.width = MAX (ra.size.width, rb.size.width);
res->size.height = MAX (ra.size.height, rb.size.height);
```

In other words, the schema shows the bounding rectangle, but the union() function does something else. That's why I said in the other bug that rectangle union was a strange operation to me.

**Comment by ebassi** [comment]
That's how the union works for two normalized rectangles: take the minimum of the origin coordinates, and take the maximum of the sizes.

**Comment by swilmet** [comment]
Note that in your schema, the blue outline is bigger than the orange rectangle.

**Comment by ebassi** [comment]
Yikes, I refactored it and completely borked, it at some point.
