### ISSUE TITLE
Vector subtract and divide: precise order of operation (a-b, a/b)

### ISSUE THREAD

**Issue by swilmet** [ebassi/graphene#54]
For graphene_vec*_subtract() and graphene_vec*_divide(), even if it's obvious it should be documented the order of the parameters in the operation, since subtract and divide are not commutative.

So, I guess the order is a-b and a/b.

**Comment by swilmet** [comment]
btw from the book that I read, vector division doesn't make sense. In graphene it's more like an array component-by-component division.

**Comment by ebassi** [comment]
Yes, the order of the arguments is the order of the operands. That's a well established behaviour, one that we also use when multiplying matrices, or multiplying matrices with vectors.

All vector operations are component operations. Like `graphene_vec[234]_multiply()`, `graphene_vec[234]_divide()` is a useful scaling operation when you have a scalar value that you want to apply to each channel in the vector — except that division may be slower, depending on the hardware.
