### ISSUE TITLE
vapigen produces invalid code

### ISSUE THREAD

**Issue by astronouth7303** [ebassi/graphene#59]
This is either a bug in vapigen or in graphene's GIRs.

I ran vapigen on the graphene gir and all the `res` arguments had `out unowned` modifiers on them. This causes vala to attempt to double-redirect for them, which is wrong.

**Comment by ebassi** [comment]
Pretty sure the introspection data is valid, so this may be a bug in the vapigen interpretation.

**Comment by astronouth7303** [comment]
Of lesser note: The header is incorrect in the gir. For some reason, it's saying the header is `graphene-object.h`.

**Comment by ebassi** [comment]
The header is correct: the GTypes for Graphene (which are used by introspection) is `graphene-gobject.h`. `graphene.h` is the pure C library.

**Comment by astronouth7303** [comment]
The header is missing the 'g'.

**Comment by ebassi** [comment]
Oh, didn't notice that. Fixed in `master`.

**Comment by astronouth7303** [comment]
I'm also discussing this in [vala #764872](https://bugzilla.gnome.org/show_bug.cgi?id=764872).

After looking at the gir, I think this is a bug in vapigen, but I'm still pretty new to vala.

**Comment by ebassi** [comment]
Closing, as the discussion is ongoing in the Vala bug tracker.
