### ISSUE TITLE
Error no such file or directory graphene-config.h

### ISSUE THREAD

**Issue by belalmedhat** [ebassi/graphene#61]
HI
I'm trying to use graphene for calculations in OpenGL program 
I opened the NetBeans and i have typed #include<graphene-1.0/graphene.h>
then build
the following error appeared 
/usr/local/include/graphene-1.0/graphene-types.h:31:29: fatal error: graphene-config.h: No such file or directory
I tried to add option to the linker like -lgraphene  or -lgraphene-1.0 and still the error appears
could you help me please
thanks in advance

**Comment by ebassi** [comment]
The `graphene-config.h` header is platform-specific, so it's installed under `lib/graphene-1.0/include`. You will have to add that path to Netbeans. If you could get Netbeans to use the pkg-config file would be even better.

**Comment by belalmedhat** [comment]
I have added the path successfully and built the program again 
there are many errors in graphene simd header files

**Comment by ebassi** [comment]
You'll have to open a separate issue for those, and specify:

 * what platform are you using
 * which compiler are you using
 * how is your build environment set up

**Comment by belalmedhat** [comment]
Thank you again i will do it Now.

**Comment by WowHowBad** [comment]
Хрш
