### ISSUE TITLE
Cannot build Graphene

### ISSUE THREAD

**Issue by belalmedhat** [ebassi/graphene#62]
OS: Ubuntu 15.04
Computer: Dell Inspiron 7520 64 bit 8GB RAM core I7 
Netbeans:
build tools: GCC
cd '/home/belal/NetBeansProjects/B3DMSIM_netbeans'
/usr/bin/make -f Makefile CONF=Debug
"/usr/bin/make" -f nbproject/Makefile-Debug.mk QMAKE= SUBPROJECTS= .build-conf
make[1]: Entering directory '/home/belal/NetBeansProjects/B3DMSIM_netbeans'
"/usr/bin/make"  -f nbproject/Makefile-Debug.mk dist/Debug/GNU-Linux/b3dmsim_netbeans
make[2]: Entering directory '/home/belal/NetBeansProjects/B3DMSIM_netbeans'
mkdir -p build/Debug/GNU-Linux
rm -f "build/Debug/GNU-Linux/cg_exp.o.d"
gcc -I/usr/local/lib/graphene-1.0/include   -c -g -std=c89 -MMD -MP -MF "build/Debug/GNU-Linux/cg_exp.o.d" -o build/Debug/GNU-Linux/cg_exp.o cg_exp.c
mkdir -p build/Debug/GNU-Linux
rm -f "build/Debug/GNU-Linux/main.o.d"
gcc -I/usr/local/lib/graphene-1.0/include   -c -g -std=c89 -MMD -MP -MF "build/Debug/GNU-Linux/main.o.d" -o build/Debug/GNU-Linux/main.o main.c
In file included from /usr/local/include/graphene-1.0/graphene.h:35:0,
                 from cg.h:15,
                 from api.h:21,
                 from main.c:9:
/usr/local/include/graphene-1.0/graphene-simd4f.h:1501:8: error: unknown type name ‘inline’
 static inline graphene_simd4f_t
        ^
/usr/local/include/graphene-1.0/graphene-simd4f.h:1502:1: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘graphene_simd4f_madd’
 graphene_simd4f_madd (const graphene_simd4f_t m1,
 ^
/usr/local/include/graphene-1.0/graphene-simd4f.h:1520:8: error: unknown type name ‘inline’
 static inline graphene_simd4f_t
        ^
/usr/local/include/graphene-1.0/graphene-simd4f.h:1521:1: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘graphene_simd4f_sum’
 graphene_simd4f_sum (const graphene_simd4f_t v)
 ^
/usr/local/include/graphene-1.0/graphene-simd4f.h:1543:15: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘float’
 static inline float
               ^
/usr/local/include/graphene-1.0/graphene-simd4f.h:1562:8: error: unknown type name ‘inline’
 static inline graphene_simd4f_t
        ^
/usr/local/include/graphene-1.0/graphene-simd4f.h:1563:1: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘graphene_simd4f_dot4’
 graphene_simd4f_dot4 (const graphene_simd4f_t a,
 ^
/usr/local/include/graphene-1.0/graphene-simd4f.h:1582:8: error: unknown type name ‘inline’
 static inline graphene_simd4f_t
        ^
/usr/local/include/graphene-1.0/graphene-simd4f.h:1583:1: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘graphene_simd4f_dot2’
 graphene_simd4f_dot2 (const graphene_simd4f_t a,
 ^
/usr/local/include/graphene-1.0/graphene-simd4f.h:1604:8: error: unknown type name ‘inline’
 static inline graphene_simd4f_t
        ^
/usr/local/include/graphene-1.0/graphene-simd4f.h:1605:1: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘graphene_simd4f_length4’
 graphene_simd4f_length4 (const graphene_simd4f_t v)
 ^
/usr/local/include/graphene-1.0/graphene-simd4f.h:1621:8: error: unknown type name ‘inline’
 static inline graphene_simd4f_t
        ^
/usr/local/include/graphene-1.0/graphene-simd4f.h:1622:1: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘graphene_simd4f_length3’
 graphene_simd4f_length3 (const graphene_simd4f_t v)
 ^
/usr/local/include/graphene-1.0/graphene-simd4f.h:1638:8: error: unknown type name ‘inline’
 static inline graphene_simd4f_t
        ^
/usr/local/include/graphene-1.0/graphene-simd4f.h:1639:1: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘graphene_simd4f_length2’
 graphene_simd4f_length2 (const graphene_simd4f_t v)
 ^
/usr/local/include/graphene-1.0/graphene-simd4f.h:1655:8: error: unknown type name ‘inline’
 static inline graphene_simd4f_t
        ^
/usr/local/include/graphene-1.0/graphene-simd4f.h:1656:1: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘graphene_simd4f_normalize4’
 graphene_simd4f_normalize4 (const graphene_simd4f_t v)
 ^
/usr/local/include/graphene-1.0/graphene-simd4f.h:1673:8: error: unknown type name ‘inline’
 static inline graphene_simd4f_t
        ^
/usr/local/include/graphene-1.0/graphene-simd4f.h:1674:1: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘graphene_simd4f_normalize3’
 graphene_simd4f_normalize3 (const graphene_simd4f_t v)
 ^
/usr/local/include/graphene-1.0/graphene-simd4f.h:1691:8: error: unknown type name ‘inline’
 static inline graphene_simd4f_t
        ^
/usr/local/include/graphene-1.0/graphene-simd4f.h:1692:1: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘graphene_simd4f_normalize2’
 graphene_simd4f_normalize2 (const graphene_simd4f_t v)
 ^
In file included from /usr/local/include/graphene-1.0/graphene-macros.h:74:0,
                 from /usr/local/include/graphene-1.0/graphene-types.h:32,
                 from /usr/local/include/graphene-1.0/graphene.h:29,
                 from cg.h:15,
                 from api.h:21,
                 from main.c:9:
/usr/local/include/graphene-1.0/graphene-simd4f.h:1709:15: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘_Bool’
 static inline bool
               ^
/usr/local/include/graphene-1.0/graphene-simd4f.h:1727:15: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘_Bool’
 static inline bool
               ^
/usr/local/include/graphene-1.0/graphene-simd4f.h:1746:15: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘_Bool’
 static inline bool
               ^
In file included from /usr/local/include/graphene-1.0/graphene.h:35:0,
                 from cg.h:15,
                 from api.h:21,
                 from main.c:9:
/usr/local/include/graphene-1.0/graphene-simd4f.h:1766:8: error: unknown type name ‘inline’
 static inline graphene_simd4f_t
        ^
/usr/local/include/graphene-1.0/graphene-simd4f.h:1767:1: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘graphene_simd4f_interpolate’
 graphene_simd4f_interpolate (const graphene_simd4f_t a,
 ^
/usr/local/include/graphene-1.0/graphene-simd4f.h:1791:8: error: unknown type name ‘inline’
 static inline graphene_simd4f_t
        ^
/usr/local/include/graphene-1.0/graphene-simd4f.h:1792:1: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘graphene_simd4f_clamp’
 graphene_simd4f_clamp (const graphene_simd4f_t v,
 ^
/usr/local/include/graphene-1.0/graphene-simd4f.h:1814:8: error: unknown type name ‘inline’
 static inline graphene_simd4f_t
        ^
/usr/local/include/graphene-1.0/graphene-simd4f.h:1815:1: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘graphene_simd4f_clamp_scalar’
 graphene_simd4f_clamp_scalar (const graphene_simd4f_t v,
 ^
/usr/local/include/graphene-1.0/graphene-simd4f.h:1835:8: error: unknown type name ‘inline’
 static inline graphene_simd4f_t
        ^
/usr/local/include/graphene-1.0/graphene-simd4f.h:1836:1: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘graphene_simd4f_min_val’
 graphene_simd4f_min_val (const graphene_simd4f_t v)
 ^
/usr/local/include/graphene-1.0/graphene-simd4f.h:1857:8: error: unknown type name ‘inline’
 static inline graphene_simd4f_t
        ^
/usr/local/include/graphene-1.0/graphene-simd4f.h:1858:1: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘graphene_simd4f_max_val’
 graphene_simd4f_max_val (const graphene_simd4f_t v)
 ^
In file included from /usr/local/include/graphene-1.0/graphene.h:36:0,
                 from cg.h:15,
                 from api.h:21,
                 from main.c:9:
/usr/local/include/graphene-1.0/graphene-simd4x4f.h:71:8: error: unknown type name ‘inline’
 static inline graphene_simd4x4f_t GRAPHENE_VECTORCALL
        ^
/usr/local/include/graphene-1.0/graphene-simd4x4f.h:72:1: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘graphene_simd4x4f_init’
 graphene_simd4x4f_init (graphene_simd4f_t x,
 ^
/usr/local/include/graphene-1.0/graphene-simd4x4f.h:95:15: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘void’
 static inline void
               ^
/usr/local/include/graphene-1.0/graphene-simd4x4f.h:114:15: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘void’
 static inline void
               ^
/usr/local/include/graphene-1.0/graphene-simd4x4f.h:134:15: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘void’
 static inline void
               ^
/usr/local/include/graphene-1.0/graphene-simd4x4f.h:205:15: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘void’
 static inline void
               ^
/usr/local/include/graphene-1.0/graphene-simd4x4f.h:226:15: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘void’
 static inline void
               ^
/usr/local/include/graphene-1.0/graphene-simd4x4f.h:255:15: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘void’
 static inline void
               ^
/usr/local/include/graphene-1.0/graphene-simd4x4f.h:283:15: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘void’
 static inline void
               ^
/usr/local/include/graphene-1.0/graphene-simd4x4f.h:308:15: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘void’
 static inline void
               ^
/usr/local/include/graphene-1.0/graphene-simd4x4f.h:328:15: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘void’
 static inline void
               ^
/usr/local/include/graphene-1.0/graphene-simd4x4f.h:357:15: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘void’
 static inline void
               ^
/usr/local/include/graphene-1.0/graphene-simd4x4f.h:381:15: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘void’
 static inline void
               ^
/usr/local/include/graphene-1.0/graphene-simd4x4f.h:450:15: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘void’
 static inline void
               ^
/usr/local/include/graphene-1.0/graphene-simd4x4f.h:485:15: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘void’
 static inline void
               ^
/usr/local/include/graphene-1.0/graphene-simd4x4f.h:525:15: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘void’
 static inline void
               ^
/usr/local/include/graphene-1.0/graphene-simd4x4f.h:559:15: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘void’
 static inline void
               ^
/usr/local/include/graphene-1.0/graphene-simd4x4f.h:591:15: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘void’
 static inline void
               ^
/usr/local/include/graphene-1.0/graphene-simd4x4f.h:646:15: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘void’
 static inline void
               ^
/usr/local/include/graphene-1.0/graphene-simd4x4f.h:670:15: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘void’
 static inline void
               ^
/usr/local/include/graphene-1.0/graphene-simd4x4f.h:694:15: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘void’
 static inline void
               ^
/usr/local/include/graphene-1.0/graphene-simd4x4f.h:743:15: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘void’
 static inline void
               ^
/usr/local/include/graphene-1.0/graphene-simd4x4f.h:764:15: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘void’
 static inline void
               ^
/usr/local/include/graphene-1.0/graphene-simd4x4f.h:787:15: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘void’
 static inline void
               ^
/usr/local/include/graphene-1.0/graphene-simd4x4f.h:808:15: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘void’
 static inline void
               ^
In file included from /usr/local/include/graphene-1.0/graphene-macros.h:74:0,
                 from /usr/local/include/graphene-1.0/graphene-types.h:32,
                 from /usr/local/include/graphene-1.0/graphene.h:29,
                 from cg.h:15,
                 from api.h:21,
                 from main.c:9:
/usr/local/include/graphene-1.0/graphene-simd4x4f.h:830:15: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘_Bool’
 static inline bool
               ^
In file included from /usr/local/include/graphene-1.0/graphene.h:36:0,
                 from cg.h:15,
                 from api.h:21,
                 from main.c:9:
/usr/local/include/graphene-1.0/graphene-simd4x4f.h:931:15: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘void’
 static inline void
               ^
In file included from /usr/local/include/graphene-1.0/graphene-macros.h:74:0,
                 from /usr/local/include/graphene-1.0/graphene-types.h:32,
                 from /usr/local/include/graphene-1.0/graphene.h:29,
                 from cg.h:15,
                 from api.h:21,
                 from main.c:9:
/usr/local/include/graphene-1.0/graphene-simd4x4f.h:993:15: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘_Bool’
 static inline bool
               ^
/usr/local/include/graphene-1.0/graphene-simd4x4f.h:1019:15: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘_Bool’
 static inline bool
               ^
nbproject/Makefile-Debug.mk:72: recipe for target 'build/Debug/GNU-Linux/main.o' failed
make[2]: *** [build/Debug/GNU-Linux/main.o] Error 1
make[2]: Leaving directory '/home/belal/NetBeansProjects/B3DMSIM_netbeans'
nbproject/Makefile-Debug.mk:60: recipe for target '.build-conf' failed
make[1]: *** [.build-conf] Error 2
make[1]: Leaving directory '/home/belal/NetBeansProjects/B3DMSIM_netbeans'
nbproject/Makefile-impl.mk:39: recipe for target '.build-impl' failed
make: *** [.build-impl] Error 2

**Comment by ebassi** [comment]
Your build flags are wrong:

```
gcc -I/usr/local/lib/graphene-1.0/include -c -g -std=c89
```

You cannot use the C89 standard to build Graphene, or to use Graphene, as it predates about 99% of the functionality Graphene uses and needs.

I recomment either `-std=gnu99` or `-std=c11`.
