### ISSUE TITLE
Error building with JHBuild

### ISSUE THREAD

**Issue by albertsmuktupavels** [ebassi/graphene#67]
I am using JHBuild to build GNOME - `jhbuild build`, but it only works if it is new clean build or I choose option `Go to phase "wipe directory and start over"`

If I want update existing modules with latest changes it always fails with error:
> *** Building graphene *** [39/196]
> make -j 9 
> CDPATH="${ZSH_VERSION+.}:" && cd . &&  -I build/autotools
> /bin/bash: -I: command not found
> Makefile:431: recipe for target 'aclocal.m4' failed
> make: *** [aclocal.m4] Error 127

**Comment by ebassi** [comment]
It seems `aclocal` is not found when you autotools decide to rebuild themselves.

I cannot reproduce locally, with or without using a separate builddir, so I honestly don't know what to say.

**Comment by albertsmuktupavels** [comment]
Don't know what has changed, but now it works.
