### ISSUE TITLE
Inspiration with blend2d - highly optimized and CPU accelerated 2D library

### ISSUE THREAD

**Issue by dumblob** [ebassi/graphene#74]
There is a highly advanced project Blend2D dealing with graphical operations being computed on CPU, but focused on 2D. It might be a good source of inspiration or even source code (though it's C++) as it has no dependencies (not even standard library) and is basically the fastest possible library for 2D graphical operations. Graphene does not necessarily provide these operations, but rather a base for them, so this is just a pointer in case it should get extended or a new thin library on top of Graphene should get created.

https://blend2d.com/

Blend2D is also based on the awesome [AsmJIT](https://github.com/asmjit/asmjit ) library from the same author.

**Comment by ebassi** [comment]
Blend2D does not even have code available at the moment, so I cannot possibly comment.

I'm definitely sure that Graphene won't acquire any API for rendering or blending; other libraries are perfectly fine for that, and they may or may not use Graphene for their data types.

This issue does not contain actionable items, so I'm going to close it.
