### ISSUE TITLE
Meson build error

### ISSUE THREAD

**Issue by sirop** [ebassi/graphene#75]
### Experienced behavior
```
master@debian-master:~/graphene/_build$ meson ..
The Meson build system
Version: 0.21.0
Source dir: /home/master/graphene
Build dir: /home/master/graphene/_build
Build type: native build

Meson encountered an error in file meson.build, line 13, column 38:
Expecting eof got lbracket.
```

### Expected behavior
Successful build with meson.

### Steps to reproduce
```
$ git clone git://github.com/ebassi/graphene
$ cd graphene
$ mkdir _build && cd _build
$ meson ..
```
### Operating system in use
```
master@debian-master:~/graphene/_build$ cat /etc/debian_version
8.4
master@debian-master:~/graphene/_build$ uname -a
Linux debian-master 3.8-1-xenomai.x86-amd64 #1 SMP Debian 3.8.13-12~1jessie~1da x86_64 GNU/Linux
master@debian-master:~/graphene/_build$ dpkg -l | grep  meson
ii  meson                                  0.21.0-1                                          all          high-productivity build system
```

**Comment by ebassi** [comment]
You are using a *very* old version of Meson — one that didn't even check the requirement for the Meson version, apparently, as Graphene [specifies the version of Meson it needs](https://github.com/ebassi/graphene/blob/master/meson.build#L9):

```
project('graphene', 'c',
        …
        meson_version: '>= 0.34.0')
```

You will need a newer version of Meson if you want to build Graphene with it.

You can install the most recent stable version of Meson using `pip3 install meson` inside a virtualenv.

**Comment by sirop** [comment]
Thanks for your answer.

So I did it with `./autogen.sh` and ` ./configure --enable-gobject-types=false --enable-debug=no` .

Could you please reveal  what the proper syntax for `--test-name` is

as I tried smth. like
```
 ./build/test-driver --test-name=quaternion_init --log-file=quatern-init.log --trs-file=quaternions_test.trs
./build/test-driver: invalid option: '--test-name=quaternion_init'
```
?

**Comment by ebassi** [comment]
If you want to run the test suite, you should use:

    $ make check

If you want to build and run a single test, then you can use:

    $ make -C src/tests quaternion
    $ ./src/tests/quaternion

The `test-driver` script is for automake's TAP integration, not a generic test harness.

**Comment by sirop** [comment]
Thanks.
