### ISSUE TITLE
Tests fail on Ubuntu's i386

### ISSUE THREAD

**Issue by jbicha** [ebassi/graphene#95]
### Experienced behavior
graphene 1.5.4 built successfully on Ubuntu 17.04 Alpha amd64 in the GNOME3 Staging PPA but the build tests failed on i386.

I used autotools for building. Here's my [packaging](https://git.launchpad.net/~jbicha/graphene/+git/ubuntu/tree/debian).

https://launchpad.net/~gnome3-team/+archive/ubuntu/gnome3-staging/+packages?field.series_filter=zesty

https://launchpadlibrarian.net/302565653/buildlog_ubuntu-zesty-i386.graphene_1.5.4-0ubuntu0~zesty1_BUILDING.txt.gz

Here's a few of the test failures:
```
ERROR: box
==========
Segmentation fault (core dumped)
# random seed: R02S18d871e89fd01da7e808a8fd4b4334b5
1..13
# Start of box tests
ERROR: box - too few tests run (expected 13, got 0)
ERROR: box - exited with status 139 (terminated by signal 11?)

ERROR: euler
============
Segmentation fault (core dumped)
# random seed: R02Se82591a0fff08197538377f6b1697611
1..2
# Start of euler tests
ERROR: euler - too few tests run (expected 2, got 0)
ERROR: euler - exited with status 139 (terminated by signal 11?)
```

**Comment by ebassi** [comment]
This looks like a compiler issue.

Your 386 packages will likely need to disable SSE instructions — and possibly vectorized GCC builtins: I'm not sure how well they work on 32 bits, and I'm not sure if anybody is even testing them.

Could you try rebuilding with `--disable-sse2` and see what happens?

**Comment by jbicha** [comment]
Thanks, it builds now with `--disable-sse2`. Do you recommend setting that for all architectures?

**Comment by ebassi** [comment]
No, I would not recommend disabling SSE support at all on any other architectures. SSE instructions work and are tested on 64bit Intel-compatible architectures, using both GCC (≥ 4.9) and Clang (≥ 3.4).

**Comment by jbicha** [comment]
@ebassi I get the same test failures with the armhf architecture but sse2 isn't used there at all.

https://launchpad.net/ubuntu/+source/graphene/1.5.4-0ubuntu1

https://launchpadlibrarian.net/304961819/buildlog_ubuntu-zesty-armhf.graphene_1.5.4-0ubuntu1_BUILDING.txt.gz

**Comment by ebassi** [comment]
This is a different issue, because on ARM you're using a different SIMD implementation (NEON).

Please, open a new issue.
