### ISSUE TITLE
graphene_quaternion_to_angles: which convention is used?

### ISSUE THREAD

**Issue by sirop** [ebassi/graphene#96]
### Experienced behavior
```
quat = graphene_quaternion_init(quat, 0.7071, 0.7071, 0, 0 ); 
graphene_quaternion_to_angles (quat,  &yaw, &pitch, &chroll);
```
yields
```
yaw = 180 
pitch  = 0
roll = -90
```
### Expected behaviour
If compared against https://github.com/matthew-brett/transforms3d
```
In [48]: np.rad2deg(quat2euler([0,0.7071,0.7071,0],axes='rzyx'))
Out[48]: array([  90.,   -0.,  180.])

In [49]: np.rad2deg(quat2euler([0,0.7071,0.7071,0],axes='szyx'))
Out[49]: array([ -90.,    0., -180.])

In [50]: np.rad2deg(quat2euler([0,0.7071,0.7071,0],axes='rxyz'))
Out[50]: array([-180.,    0.,  -90.])

In [51]: np.rad2deg(quat2euler([0,0.7071,0.7071,0],axes='sxyz'))
Out[51]: array([ 180.,   -0.,   90.])

In [52]: np.rad2deg(quat2euler([0,0.7071,0.7071,0],axes='szxy'))
Out[52]: array([  90.,   -0.,  180.])

In [53]: np.rad2deg(quat2euler([0,0.7071,0.7071,0],axes='rzxy'))
Out[53]: array([ -90.,    0., -180.])

In [54]: np.rad2deg(quat2euler([0,0.7071,0.7071,0],axes='ryxz'))
Out[54]: array([ 180.,   -0.,   90.])

In [55]: np.rad2deg(quat2euler([0,0.7071,0.7071,0],axes='syxz'))
Out[55]: array([-180.,    0.,  -90.])

In [56]: np.rad2deg(quat2euler([0,0.7071,0.7071,0],axes='szxy'))
Out[56]: array([  90.,   -0.,  180.])
```
one finds no triple with one of the angles being -90 and the other 180 degrees.
`q[0]` corresponts to graphene's `q.w` .

I am pretty sure about https://github.com/matthew-brett/transforms3d as I checked `quat2euler(q,axes='rzyx')` case  before with quaternion and Yaw-Pitch-Roll output of my gyro.

### Operating system in use
debian 8

### SIMD implementation in use
SSE

**Comment by sirop** [comment]
Just seen `graphene_euler_init_from_quaternion (...)` .
Will try this out.

**Comment by ebassi** [comment]
The `to_angles()` function is definitely less flexible than conversion from `graphene_quaternion_t` to a `graphene_euler_t` (and vice versa). It would definitely be great to amend the documentation to say that, though. I'll try to get a fix in.

**Comment by sirop** [comment]
These quaternion-euler conversion functions do not seem to make much use of any SIMD features.
So worth porting https://github.com/matthew-brett/transforms3d/blob/master/transforms3d/euler.py to graphene, also in order to supper all 24 Euler angles combinations?

**Comment by sirop** [comment]
although the python code is ported from https://github.com/erich666/GraphicsGems/tree/master/gemsiv/euler_angle .

**Comment by ebassi** [comment]
Is there any particular case that isn't covered by `graphene_euler_t` and the rotation order?

**Comment by sirop** [comment]
If I may quote http://matthew-brett.github.io/transforms3d/reference/transforms3d.euler.html

> Each of the two groups (intrinsic and extrinsic) can further be divided into so-called Euler rotations (rotation about one axis, then a second and then the first again), and Tait-Bryan angles (rotations about all three axes). The two groups (Euler rotations and Tait-Bryan rotations) each have 6 possible choices. There are therefore 2 * 2 * 6 = 24 possible conventions that could apply to rotations about a sequence of three given angles.

A for now only Tait-Bryan rotations are within `graphene_euler_order_t` enum.
